
name: cnc-sig-action
on:
  pull_request:
    branches: [ main, master, develop, stage, release ]
jobs:
  build:
    runs-on: [ linux ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
          
      - name: Coverity PR Scan
        uses: synopsys-sig/synopsys-action@main
        with:
          coverity_url: ${{ secrets.COVERITY_URL }}
          coverity_user: ${{ secrets.COVERITY_USER }}
          coverity_passphrase: ${{ secrets.COVERITY_PASSPHRASE }}
          coverity_project_name: ${{ github.event.repository.name }}
          coverity_stream_name: ${{ github.event.repository.name }}-${{ github.base_ref }}
          ### Below configuration is used to enable feedback from Coverity security testing as pull request comment
          coverity_automation_prcomment: true
          coverity_local: true
          github_token: ${{ secrets.GITHUB_TOKEN }} # Mandatory when coverity_automation_prcomment is set to 'true'   
          ### Uncomment below configuration if Synopsys Bridge diagnostic files needs to be uploaded
          include_diagnostics: true
          coverity_version: '2023.3.2'
